name: Deploy Telegram Bot

on:
  push:
    branches:
      - main # Действие срабатывает при пушах в главную ветку
  schedule:
    - cron: '0 */4 * * *' # Каждое начало часа каждые 4 часа

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Run bot application
        run: npm start
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          ADMIN_ID: ${{ secrets.ADMIN_ID }}
          VIP_PASSWORD: ${{ secrets.VIP_PASSWORD }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          AI_INTEGRATIONS_OPENAI_BASE_URL: ${{ secrets.AI_INTEGRATIONS_OPENAI_BASE_URL }}
          AI_INTEGRATIONS_OPENAI_API_KEY: ${{ secrets.AI_INTEGRATIONS_OPENAI_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
